## `Numpy (Numerical Python)`
- Numerical Python

- used for working with arrays.
- List serves the purpose of the arrays in python, but are significantly slow.
- Stored at one continous place in memory unlike lists. That's why numpy is faster to process, efficient to access, and manipulate.
- partially written in python but the part which require fast computation are written in C or C++.

- Array object in Numpy is `ndarray`. 

- The array-like objects in python like list and tuple can be converted into numpy array.

#### &emsp; `Package installation`
```python
    # Type
    pip install numpy
    # in command prompt after activating the environment.
```

In [2]:
# check numpy version
import numpy as np
print(np.__version__)

1.23.5


In [3]:
# Create ndarray object using array() function
arr = [1, 2, 3, 4]
np_arr = np.array(arr)
print(type(np_arr), np_arr)

<class 'numpy.ndarray'> [1 2 3 4]


#### `Determine shape of array with 'shape' attribute`

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.shape)

In [ ]:
arr = np.array(
    [[1, 2, 3], [3, 4, 5]]
)
print(arr.shape)

#### `What does shape tuple represents?`
- Integers at every index represents the number of elements present in its corresponding dimension.

#### `Dimensions in Numpy Array`

#### &emsp;`0-D Arrays`
- The arrays are scalers with no shape.

In [ ]:
arr = np.array(10)

print(arr)
# print(type(arr))
# print(arr.shape)

#### &emsp;`1-D Arrays`
- The arrays consists 0-D arrays as its elements.

In [ ]:
arr = np.array([11, 12, 13, 14, 15])

print(arr)
# print(type(arr))
# print(arr.shape)

#### &emsp;`2-D Arrays`
- The arrays consists 1-D arrays as its elements.
- Represents matrix

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
# print(type(arr))
# print(arr.shape)

#### &emsp;`3-D Arrays`
- The arrays consists 2-D arrays as its elements.

In [4]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
# print(type(arr))
# print(arr.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


#### &emsp;Determine number of dimensions of `ndarray` object.

In [6]:
arr_1 = np.array(42)
arr_2 = np.array([1, 2, 3, 4, 5])
arr_3 = np.array([[1, 2, 3], [4, 5, 6]])
arr_4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print('Num of dim in arr_1: ', arr_1.ndim)
print('Num of dim in arr_2: ', arr_2.ndim)
print('Num of dim in arr_3: ', arr_3.ndim)
print('Num of dim in arr_4: ', arr_4.ndim)

Num of dim in arr_1:  0
Num of dim in arr_2:  1
Num of dim in arr_3:  2
Num of dim in arr_4:  3


#### &emsp;Higher Dimension in Arrays
- When creating numpy array using `array()`, it is possible to create array of any dimension with the use of `ndmin` argument.

In [1]:
import numpy as np

arr = np.array([21, 22, 23, 24], ndmin=6)

print(arr)
print('Num of dim in arr: ', arr.ndim)

[[[[[[21 22 23 24]]]]]]
Num of dim in arr:  6


## `Numpy Array Indexing`
- Access elements in array using index number.
- Index starts from 0.

#### &emsp;`Accessing 1-D Array`

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])
print(arr[1])

#### &emsp;`Accessing 2-D Array`

In [3]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0, 1])

2


#### &emsp;`Accessing 3-D Array`

In [5]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 1])

5


#### &emsp;`Negative Indexing`

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[-1])

#### &emsp;`Array Slicing`
- &emsp;&emsp;array_name[_start-index_:_end-index_]<br/>
- &emsp;&emsp;array_name[_start-index_:_end-index_:_step_]

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(arr[1:5])
print(arr[1:])
print(arr[:3])

[[ 6  7  8  9 10]]
[[ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### &emsp;`Negative Indexing`

In [ ]:
print(arr[-4:-3])
print(arr[-2:])
print(arr[:-5])

#### &emsp;`Step`

In [ ]:
print(arr[0:6:1])
print(arr[0:6:2])
print(arr[::2])

In [ ]:
print(arr[-4::2])
print(arr[::-1])

#### &emsp;`Slicing 2-D Array`

In [ ]:
arr = np.array([[1, 2, 3, 4, 5, 6],[7, 8, 9, 10, 11, 12]])
print(arr)

In [ ]:
print(arr[0, 1:6])
print(arr[0:2, 0])

In [ ]:
print(arr[:, 0])

#### &emsp; `Data Types in Numpy`
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- M - datetime
- S - string

#### &emsp;`Check data type`

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

In [ ]:
arr = np.array([1, 'banana', 'cherry'], dtype='i')
print(arr.dtype)

#### &emsp;`Converting Data Type of Existing Array`

In [ ]:
arr = np.array([5.8, 6.4, 7.3])
new_arr = arr.astype('i')
print(new_arr)
print(new_arr.dtype)

In [ ]:
arr = np.array([5, 6, 7])
new_arr = arr.astype('f')
print(new_arr)
print(new_arr.dtype)

#### `Copy and View`
- Main Difference: `copy()` creates array in new object location while `view()` provides reference to original array. 
- changes in original array aren't seen in new array created with `copy()` and vice-versa but seen in array created with `view()`.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

x = arr.copy()
arr[0] = 42

print(arr)
print(x)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

#### `Reshape`
- arrange the elements in different dimensions.
- total number of elements should be equal to product of all dimensions.

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
# 1d-2d 
arr2 = arr.reshape(3, 4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# 1d-3d
arr3 = arr.reshape(2, 2, 3)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [10]:
arr0 = arr3.reshape(-1)
print(arr0)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
arr3 = arr.reshape(2, 2, -1)
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
print(arr3.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### `Iterating over Arrays`
- going through the each of the elements one at a time

In [15]:
# Iterating on 1-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8 , 9, 10, 11, 12])

for ele in arr:
    print(f"element is: {ele}\n")

element is: 1

element is: 2

element is: 3

element is: 4

element is: 5

element is: 6

element is: 7

element is: 8

element is: 9

element is: 10

element is: 11

element is: 12



In [16]:
# Iterating on 2-D array
arr = arr.reshape(3, 4)
print(arr)

for ele in arr:
    print(f"\nelement is: {ele}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

element is: [1 2 3 4]

element is: [5 6 7 8]

element is: [ 9 10 11 12]


In [17]:
# Iterating on 3-D array
arr = arr.reshape(2, 2, 3)
print(arr)

for ele in arr:
    print(f"\nelement is: {ele}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

element is: [[1 2 3]
 [4 5 6]]

element is: [[ 7  8  9]
 [10 11 12]]


In [18]:
# Iterating down to scalers for array having
# dimension greater than 1
arr = arr.reshape(3, 4)

# vanilla method
for row in arr:
    for j in row:
        print(f'element {j}')

element 1
element 2
element 3
element 4
element 5
element 6
element 7
element 8
element 9
element 10
element 11
element 12


In [19]:
# Iterating using nditer()
for x in np.nditer(arr):
    print(f'nditer  element {x}')

nditer  element 1
nditer  element 2
nditer  element 3
nditer  element 4
nditer  element 5
nditer  element 6
nditer  element 7
nditer  element 8
nditer  element 9
nditer  element 10
nditer  element 11
nditer  element 12


In [20]:
step = 2
print(arr[:, ::step])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [21]:
# Iterating with different step size
for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7
9
11


In [ ]:
# Iterating with np.ndenumerate()
for idx, x in np.ndenumerate(arr):
  print(idx, x)

#### `Joining Arrays` 

In [22]:
# Joining with concatinate() for 1-D
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [23]:
# Joining with concatinate() for 2-D
# axis -> 0 is along 1st dimension
# axis -> 1 is along 2nd dimension
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [24]:
# Joining with stack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# Joining with stack()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# axis=-1 for last dimension
arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# Joining with stack()
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.stack((arr1, arr2), axis=0)
arr

In [26]:
# Joining with stack()
arr1 = np.array([[1, 2, 3], [4, 5, 6], [13, 14, 15]])
arr2 = np.array([[7, 8, 9], [10, 11, 12], [16, 17, 18]])

arr = np.stack((arr1, arr2), axis=2)
arr

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]],

       [[13, 16],
        [14, 17],
        [15, 18]]])

In [ ]:
# Joining with stack()
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# axis=-1 for last dimension
arr = np.stack((arr1, arr2), axis=-1)
arr

#### `Stacking with helper functions 'hstack()' 'vstack()' 'dstack()`

In [ ]:
# Stacking along rows
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.hstack((arr1, arr2))
arr

In [ ]:
# Stacking along columns
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.vstack((arr1, arr2))
arr

In [ ]:
# Stacking along depth
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

arr = np.dstack((arr1, arr2))
arr

#### `Splitting with array_split()`
- returns list containing arrays

In [ ]:
# Splitteing 1-D arrays
num_of_splits = 2
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
new_arr = np.array_split(arr, num_of_splits)
new_arr

In [ ]:
# Splitteing 2-D arrays
num_of_splits = 2
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
new_arr = np.array_split(arr, num_of_splits)
new_arr

#### `Splitting with hsplit(), vsplit(), dsplit()`
- returns list containing arrays

In [ ]:
# Splitteing 2-D arrays
num_of_splits = 2
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
new_arr = np.vsplit(arr, num_of_splits)
new_arr

In [ ]:
# Splitteing 2-D arrays
num_of_splits = 2
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
new_arr = np.hsplit(arr, num_of_splits)
new_arr

In [ ]:
# dsplit() works for array with dimension equal or greater than 3.
num_of_splits = 2
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
new_arr = np.dsplit(arr, num_of_splits)
new_arr

#### `Search elements in array` 

In [ ]:
# in 1-D Array
arr = np.array([1, 2, 3, 4, 5, 3, 3])
x = np.where(arr == 3)

print(x)

In [ ]:
# in 2-D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
x = np.where(arr == 3)

print(x)

In [ ]:
# in 2-D array
arr = np.array([[1, 2], [3, 4], [3, 6], [7, 8]])
x = np.where(arr == [3, 4])

print(x)

In [ ]:
# find even elements in array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)

print(x)

#### `Sorting numpy arrays with sort()`
- returns copy of original array leaving original array unchanged.

In [ ]:
# sorting 1-D array
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

In [ ]:
# sorting boolean array
arr = np.array([True, False, True])
print(np.sort(arr))

In [ ]:
# Sorting string array
arr = np.array(['Python', 'Java', 'Js', 'Mojo'])
print(np.sort(arr))

In [ ]:
# sorting string array
arr = np.array(['Python', 'Java', 'JS', 'Mojo'])
print(np.sort(arr))

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

#### `Filtering numpy arrays`
- excluding or including elements from existing array based on some condition.
- index with boolean value `True` is included
- index with boolean value `False` is excluded

In [ ]:
# hardcoded index
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
new_arr = arr[x]
new_arr

In [ ]:
# conditional filer with for loop
arr = np.array([41, 42, 43, 44])
new_arr = []
for ele in arr:
    if ele > 42:
        new_arr.append(ele)
print(new_arr)

In [ ]:
# conditional filter
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
new_arr = arr[filter_arr]
new_arr